### ISSUE TITLE
Updates to docs re: qctool

### ISSUE THREAD

**Issue by gavinband** [explodecomputer/data_manipulation#1]
Hi,
I came across this after searching for 'ALSPAC bgen', and just wanted to update with a note that (if I understand the task right), qctool should be able to do the merging you refer to - something like this:

`qctool -g data_chr#.bgen -s data.sample -incl-samples idlist.txt -incl-rsids snplist.txt -og extracted.bgen`

should do it.

(See http://www.well.ox.ac.uk/~gav/qctool for docs.)

Also - there are now other tools (including an R package) that can be used to deal with this sort of task - see http://www.bitbucket.org/gavinband/bgen for more.

Best wishes,
g.

**Comment by explodecomputer** [comment]
Terrific, thanks very much! I think the scripts in this repo are largely redundant, have updated the readme.
